apiVersion: apps/v1
kind: Deployment
metadata:
  name: webs-deployment
  labels:
    app: test1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1
        image: mcwacr.azurecr.io/webs
        ports:
        - containerPort: 80
